services:
    mysqldb:
        image: mysql:5.7
        container_name: todosimple-mysql
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        expose:
            - $MYSQL_DOCKER_PORT
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10